#!/usr/bin/env node
/**
 * TOKEN BUILD — a real, working reference implementation of workflows/token-build.md.
 * Reads the DTCG tokens in tokens/*.json (source of truth), resolves every alias
 * (incl. cross-file {../colors.*} and the dark override map), and emits a single
 * CSS-variable theme: `:root { … }` + `:root[data-theme="dark"] { … }`.
 *
 * Scope: the color system (semantic + component + dark) — the most-used layer and
 * where the CSS-var naming is unambiguous (semantic.action.primary → --color-action-primary).
 * Extend the EMIT map below for other token files.
 *
 * Usage:
 *   node scripts/build_tokens.mjs            # DTCG kit samples → CSS (stdout)
 *   node scripts/build_tokens.mjs --out dist/tokens.css
 *
 * Project mode (this repo's REAL neutral theme is the source of truth):
 *   node scripts/build_tokens.mjs --from-css app/globals.css            # re-emit real :root + .dark
 *   node scripts/build_tokens.mjs --from-css app/globals.css --json     # canonical {name:{light,dark}} map
 *   …--from-css app/globals.css --json --out dist/tokens.json           # for platform/framework export
 */
import { readFileSync, readdirSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

// fileURLToPath decodes %20 etc. — works when the project path contains spaces.
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TOKENS = join(ROOT, 'tokens');
const out = (process.argv.find(a => a.startsWith('--out=')) || '').split('=')[1]
  || (process.argv.includes('--out') ? process.argv[process.argv.indexOf('--out') + 1] : null);
const fromCss = (process.argv.find(a => a.startsWith('--from-css=')) || '').split('=')[1]
  || (process.argv.includes('--from-css') ? process.argv[process.argv.indexOf('--from-css') + 1] : null);
const asJson = process.argv.includes('--json');

// === Project mode: source the REAL neutral-theme tokens straight from globals.css ===
// The project's source of truth is the oklch CSS vars in :root {} (light) + .dark {} (dark),
// not the kit's DTCG samples. This makes downstream platform/framework export reflect the real theme.
if (fromCss) {
  const css = readFileSync(resolve(fromCss), 'utf8');
  const block = (re) => {                       // grab a balanced { … } block by selector
    const i = css.search(re);
    if (i < 0) return {};
    const open = css.indexOf('{', i);
    let depth = 0, end = open;
    for (let j = open; j < css.length; j++) {
      if (css[j] === '{') depth++;
      else if (css[j] === '}' && --depth === 0) { end = j; break; }
    }
    const map = {};
    for (const m of css.slice(open + 1, end).matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)) map[m[1]] = m[2].trim();
    return map;
  };
  const light = block(/(^|\s):root\s*\{/m);     // real values (NOT @theme inline aliases)
  const dark = block(/(^|\s)\.dark\s*\{/m);
  const names = [...new Set([...Object.keys(light), ...Object.keys(dark)])];
  if (names.length === 0) { console.error(`No :root tokens found in ${fromCss}`); process.exit(1); }

  let payload, summary;
  if (asJson) {
    const obj = {};
    for (const n of names) obj[n.replace(/^--/, '')] = { light: light[n] ?? null, dark: dark[n] ?? light[n] ?? null };
    payload = JSON.stringify(obj, null, 2) + '\n';
    summary = `wrote ${names.length} tokens (light+dark) as JSON`;
  } else {
    const fmt = (m) => Object.entries(m).map(([k, v]) => `  ${k}: ${v};`).join('\n');
    payload = `/* Generated by build_tokens.mjs --from-css ${fromCss} — REAL project tokens, do not edit by hand. */\n`
      + `:root {\n${fmt(light)}\n}\n.dark {\n${fmt(dark)}\n}\n`;
    summary = `wrote ${Object.keys(light).length} light + ${Object.keys(dark).length} dark vars`;
  }
  if (out) { mkdirSync(dirname(resolve(out)), { recursive: true }); writeFileSync(resolve(out), payload); console.log(`${summary} → ${out}`); }
  else process.stdout.write(payload);
  process.exit(0);
}

// 1) load every token file into a global path->value map (file-namespaced + bare)
const all = {};
for (const f of readdirSync(TOKENS).filter(n => n.endsWith('.json'))) {
  const data = JSON.parse(readFileSync(join(TOKENS, f)));
  const stem = f.replace(/\.json$/, '');
  (function walk(o, p) {
    if (o && typeof o === 'object') {
      if ('$value' in o) { all[p] = o.$value; all[`${stem}.${p}`] = o.$value; }
      for (const k of Object.keys(o)) if (!k.startsWith('$')) walk(o[k], p ? `${p}.${k}` : k);
    }
  })(data, '');
}

// 2) resolve a value (follow {ref} chains incl. ../ and file prefixes)
function res(v, depth = 0) {
  if (depth > 16 || typeof v !== 'string') return v;
  const m = v.match(/^\{(.+)\}$/);
  if (!m) return v;
  let ref = m[1].trim();
  while (ref.startsWith('../') || ref.startsWith('./')) ref = ref.startsWith('../') ? ref.slice(3) : ref.slice(2);
  let val = all[ref];
  if (val === undefined) { const tail = ref.split('.').slice(1).join('.'); val = all[ref] ?? all[tail]; }
  return val === undefined ? v : res(val, depth + 1);
}

// 3) emit semantic + component color tokens as --color-* ; dark section as overrides
const colors = JSON.parse(readFileSync(join(TOKENS, 'colors.json')));
const lines = { light: [], dark: [] };
function emit(obj, prefix, bucket) {
  for (const [k, v] of Object.entries(obj || {})) {
    if (k.startsWith('$')) continue;
    if (v && typeof v === 'object' && '$value' in v) {
      const hex = res(v.$value);
      if (typeof hex === 'string' && /^(#|rgb|hsl)/.test(hex)) lines[bucket].push(`  --color-${prefix}${k}: ${hex};`);
    } else if (v && typeof v === 'object') {
      emit(v, `${prefix}${k}-`, bucket);
    }
  }
}
emit(colors.semantic, '', 'light');
if (colors.component) emit(colors.component, '', 'light');
if (colors.dark) emit(colors.dark, '', 'dark');

const css = `/* Generated by scripts/build_tokens.mjs from tokens/*.json — do not edit by hand. */
:root {
${[...new Set(lines.light)].join('\n')}
}
:root[data-theme="dark"] {
${[...new Set(lines.dark)].join('\n')}
}
`;

if (out) {
  mkdirSync(dirname(resolve(out)), { recursive: true });
  writeFileSync(resolve(out), css);
  console.log(`wrote ${[...new Set(lines.light)].length} light + ${[...new Set(lines.dark)].length} dark color vars → ${out}`);
} else {
  process.stdout.write(css);
}
