#!/usr/bin/env node
/**
 * Build the COMPONENT tier of the DTCG tokens (tokens/*.tokens.json) into CSS
 * custom properties → app/tokens.generated.css (imported by globals.css).
 *
 *   npm run tokens:build
 *
 * Why only the component tier is emitted: the primitive + semantic tiers already
 * live in globals.css as the Figma-synced :root/.dark CSS variables (the neutral
 * theme is the source of truth). This script wires the third tier on top so
 * components consume `var(--button-default-bg)` etc. — and, crucially, when a
 * component token aliases a SEMANTIC role it emits `var(--<role>)` (NOT the
 * resolved literal), so the value still flips automatically in dark mode.
 * Primitive aliases and raw values (overlays, durations) are inlined as literals.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const tokensDir = join(root, "tokens");
const outFile = join(root, "app/tokens.generated.css");

const files = readdirSync(tokensDir).filter((f) => f.endsWith(".tokens.json"));
const docs = files.map((f) => JSON.parse(readFileSync(join(tokensDir, f), "utf8")));

// Flat index of every token by dotted path (for alias resolution).
const index = new Map();
const indexTree = (node, path) => {
  if (node && typeof node === "object" && "$value" in node) {
    index.set(path.join("."), node);
    return;
  }
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith("$")) continue;
    if (v && typeof v === "object") indexTree(v, [...path, k]);
  }
};
for (const doc of docs) indexTree(doc, []);

const isAlias = (v) => typeof v === "string" && /^\{[^}]+\}$/.test(v);
const aliasPath = (v) => v.slice(1, -1);
const bezier = (arr) => `cubic-bezier(${arr.join(", ")})`;

// Resolve a token value to a CSS string.
// Semantic aliases → var(--role) (mode-aware). Primitive aliases / literals → inlined.
const toCss = (value) => {
  if (Array.isArray(value)) return value.join(", "); // fontFamily / cubicBezier handled below
  if (isAlias(value)) {
    const segs = aliasPath(value).split(".");
    if (segs[0] === "semantic") return `var(--${segs.slice(1).join("-")})`;
    // primitive (or any non-semantic) alias → resolve to its literal value
    const target = index.get(aliasPath(value));
    if (!target) throw new Error(`Unresolved alias: ${value}`);
    if (Array.isArray(target.$value)) {
      return target.$type === "cubicBezier" ? bezier(target.$value) : target.$value.join(", ");
    }
    return toCss(target.$value);
  }
  return value; // literal: oklch(...), 150ms, transparent, etc.
};

// Walk each doc's `component` subtree → flat CSS var declarations.
const decls = [];
const walkComponent = (node, path) => {
  if (node && typeof node === "object" && "$value" in node) {
    const name = path.join("-");
    let css;
    if (node.$type === "cubicBezier" && Array.isArray(node.$value)) css = bezier(node.$value);
    else css = toCss(node.$value);
    decls.push(`  --${name}: ${css};`);
    return;
  }
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith("$")) continue;
    if (v && typeof v === "object") walkComponent(v, [...path, k]);
  }
};
for (const doc of docs) if (doc.component) walkComponent(doc.component, []);

decls.sort();
const out = `/* AUTO-GENERATED by scripts/build-tokens.mjs from tokens/*.tokens.json — run \`npm run tokens:build\`. Do not edit. */
/* Component-tier design tokens. Semantic aliases resolve to var(--role) so they stay mode-aware (light/dark). */
:root {
${decls.join("\n")}
}
`;
writeFileSync(outFile, out);
console.log(`Wrote ${decls.length} component tokens → app/tokens.generated.css`);
